### ISSUE TITLE
Select element with pre-selected value not rendering correctly

### ISSUE THREAD

**Issue by evergreenwebsystems** [calebporzio/livewire#85]
Describe the bug:
A select element with a pre selected value does not render correctly for the user

To Reproduce
1. Create a blade template with a select element
2. Pass a value from livewire to the blade template
3. Use standard blade syntax to set the pre-selected value

Expected result:
If the second option in the select element is selected then this should be visible to the user when the dom renders.

Actual result:
Always the first option in the select element is visible to the user even though another option has the correct html selected tag.

Blade Input:
```
<select id="role_id" wire:model="role_id">
    <option value="1" {{ $role_id == 1 ? 'selected="selected"' : '' }}>Owner</option>
    <option value="2" {{ $role_id == 2 ? 'selected="selected"' : '' }}>Collaborator</option>
</select>
```

HTML Output
```
<select id="role_id" wire:model="role_id">
    <option value="1">Owner</option> 
    <option value="2" selected="selected">Collaborator</option>
</select>
```

Screenshots
![image](https://user-images.githubusercontent.com/8020291/62048843-27e33a00-b20e-11e9-8322-818c18ffc028.png)

Desktop (please complete the following information):
 - Browser: chrome

**Comment by davidpiesse** [comment]
Hi,

Try with just a selected like this link suggests.
https://www.w3schools.com/tags/att_option_selected.asp

It may be the selected="selected" is not the right syntax.

Let me know how it goes :)

David

**Comment by evergreenwebsystems** [comment]
Unfortunately that didn't work. If I remove the `wire:model="role_id"` from the select element then the correct value is displayed but then obviously it doesn't work anymore in terms of saving changes via livewire.

**Comment by davidpiesse** [comment]
Good to know!

If you have anything else that does / doesn't work please let us know.
Helps focus the search!

David

**Comment by evergreenwebsystems** [comment]
Everything else works just as expected. Data is saved correctly.

Interestingly, if I try and create a new record using the form and dont touch the select element at all, just skip it and press save, then I get an `Integrity constraint violation: 1048 Column 'role_id' cannot be null`, but if I click into the select element and change the value then it works as expected. 

So, it seems like livewire isn't picking up the initial state of the select element until it is clicked and changed at least once.

If it helps at all here is my code:

Livewire controller:
```
class ProjectsEdit extends Component
{
    public $id;
    public $title;
    public $description;
    public $role_id;

    public function mount($id)
    {
        $project = Project::find($id);

        $this->id = $project->id;
        $this->title = $project->title;
        $this->description = $project->description;
        $this->role_id = $project->role->role_id;
    }

    public function updateProject($id)
    {
        $attributes = $this->validate([
            'title' => 'required|min:10',
            'description' => 'required|min:10',
        ]);

        Project::find($id)->update($attributes);
        Project::find($this->id)->users()->updateExistingPivot(auth()->user(), ['role_id' => $this->role_id]);

        $this->emit('renderProjects');
        $this->emit('closeModal');
    }

    public function render()
    {
        return view('livewire.projects-edit');
    }
}
```

Live wire blade template:
```
<div>

    <!--Title-->
    <div class="flex justify-between items-center pb-3">
        <p class="text-2xl font-bold">Edit Project</p>
    </div>

    <div class="mb-4">
        <label>Title*</label>
        <input type="text" id="title" placeholder="Project title"
            value="{{old('title', $title)}}" wire:model="title">
        @if ($errors->has('title'))
        <p class="text-red-500 text-s italic">{{ $errors->first('title') }}</p>
        @endif
    </div>

    <div class="mb-4">
        <label>Description*</label>
        <textarea id="description" rows="6" placeholder="Project description"
            wire:model="description">{{old('description', $description)}}</textarea>
        @if ($errors->has('description'))
        <p class="text-red-500 text-s italic">{{ $errors->first('description') }}</p>
        @endif
    </div>

    <div class="mb-4">
        <label>Role*</label>
        <select
            id="role_id" wire:model="role_id">
            <option value="1" {{ $role_id == 1 ? 'selected="selected"' : '' }}>Owner</option>
            <option value="2" {{ $role_id == 2 ? 'selected="selected"' : '' }}>Collaborator</option>
        </select>
    </div>

    <div>
        <button type="submit"
            wire:click="updateProject({{ $id }})">
            Update Project
        </button>
        <span class="font-bold text-gray-500 pl-4" wire:click="$emit('closeModal')">Cancel</span>
    </div>

</div>
```

**Comment by calebporzio** [comment]
@evergreenwebsystems - this should be fixed in the latest release.

I think the problem is that `$role_id` needs to be a string, and you were setting it to a numeric value. I fixed livewire to handle strings to set the value of a select input.

This should be fixed in the latest release (will probably be in v0.1.2)

Also, Livewire intelligently sets selected states, so you can get rid of the manually echoing out `selected="selected"`

**Comment by evergreenwebsystems** [comment]
Setting `$role_id` as a string does indeed fix the issue. Amazing that it also intelligently sets the selected state.

Thanks!

**Comment by LewisLarsen** [comment]
I have just encountered the same issue, my column was set to integer and it wouldn't pass the pre-selected ID to the component. I had to click on another option in the select to "fix" it and then it would pass it.

Changing the column type to string didn't fix the issue sadly, a work around is to have a placeholder, to force the user to select an option.
i.e. `<option value="" selected>Select a category</option>`

**Comment by roni-estein** [comment]
@LewisLarsen I use that without issue
`<option value="">Select a category</option>` (make sure to remove the selected) and set your wire:model item to '' in your component and have it validate to an integer if you want to force a choice

alternatively you can set the default value to -1
<option value="-1">Select a category</option>
 
validate you item to 'required|numeric|min:1'
or 'digits_between:1,x' for example if you have X elements and each element is increasing in value. go with the first one :)

**Comment by smartnathan** [comment]
Please, am having this same issue, can have the default selected city, when I want to change the city. Here is my code:
### Live wire view template
`<select wire:model="user_city" id="user_city" class="form-control" required="required">
           <option value=''>--Select Delivery City--</option>
           @foreach ($cities as $item)
           
           <option {{ (isset($search) && $item->id == $search->delivery_location_id) ? 'selected' : "" }} value="{{ $item->id }}, {{ $item->state_id}}">{{ $item->state->name }} State - {{ $item->name }} {{ $search->delivery_location_id }} | {{ $item->id }}</option>
          
           @endforeach
       </select>`

### Live wire Component
`class Intro extends Component
{
	public $user_city='';

    public function render()
    {
        $cities = City::select('id', 'name', 'state_id')->get();

        if (session('client_ip_address')) {
        	//dd("Hello");
        	$search = Search::where("ip_address", session('client_ip_address'))->latest()->first();
        	//dd($search);
        }

        return view('livewire.pages.intro', compact('cities', 'search'));
    }
`

**Comment by martin-ro** [comment]
> Also, Livewire intelligently sets selected states, so you can get rid of the manually echoing out `selected="selected"`

How and where? I could find nothing in the documentation.

**Comment by zendzo** [comment]
> @LewisLarsen I use that without issue
> `<option value="">Select a category</option>` (make sure to remove the selected) and set your wire:model item to '' in your component and have it validate to an integer if you want to force a choice
> 
> alternatively you can set the default value to -1
> `<option value="-1">Select a category</option>`
> 
> validate you item to 'required|numeric|min:1'
> or 'digits_between:1,x' for example if you have X elements and each element is increasing in value. go with the first one :)

i had sama issue, and this is one of the tricks to solve this problem. Thanks

**Comment by jiteshdhamaniya** [comment]
No, this does not work. "livewire/livewire": "^2.2", "laravel/framework": "^7.24".
I have tried converting value to string as well. it selects but wrong one. 

```
$this->status = (string) $this->user->status;
$this->platform = (string) $this->user->platform;
```

When and setting value in blade
```
 @php
     $statues__ = ['Un-Approved','Approved','Blocked'];
 @endphp

 <x-users.select wire:model="status"
                    name="status" required="true" label="User Status" value={{ $status }}>
                    @foreach ($statues__ as $key => $s_item)
                        <option value="{{ $key }}">
                            {{ $s_item }}
                        </option>
                    @endforeach
```
and it selects Approved for Blocked user.

**Comment by maciej2303** [comment]
It's still isn't fixed.

**Comment by GigaMick** [comment]
14th October 2020 still not working.

If I do this:

```
<option value="{{$g->token}}" @if($track->group->token == $g->token) selected @endif>{{$g->name}} </option>
```

Nothing is selected. However if I change it "disabled" NOTE: changing nothing except what is inside the if statement from "selected" to "disabled" like this

```
<option value="{{$g->token}}" @if($track->group->token == $g->token) disabled @endif>{{$g->name}} </option>
```

Then the correct option is disabled.

So the logic if working, the string "selected" is being output in the correct place. It's just simply not working.

**Comment by jiteshdhamaniya** [comment]
Ok I figured this. 
to anybody who is still looking. 

```
<select wire:model="status">
                        <option value="1">  Approved </option>
                        <option value="2">  Un-Approved </option>
</select>
```
That's all you have to do. But initially it won't be having any value, so you have to set value in mount method like this 

```
public function mount(){
   $this->status = 1;
}

```
and then It will be automatically selected. You can do this in render method too incase you want to set every time component refreshes.

**Comment by dominiquevilain** [comment]
@jiteshdhamaniya What you are describing is a doc. like case, and of course it works ! That’s the beauty of it.

But what about graceful degradation ?

I teach web techs and feel concerned about web quality. I have decided to drop VueJS from my teachings and I have replaced it with Livewire because it allows easily graceful degradation where other frameworks taking full control of everything simply break when JS is not there.

So that’s the context. Every exercise I make is tested with AND without JS.

When handling with select fields, it becomes a bit weird though… 

Without JS, I can't rely on the `wire:model` magic… So it's necessary to test if every option matches the context to apply a `select` attribute to the chosen one. It works great without JS of course, but not _with_  JS anymore. In this scenario, when I re-activate JS, I get this weird interaction, where the option looks correctly selected at first (thanks to the test) but then immediately deselected (By JS I guess) and finally nothing (it’s empty) shows up in the select field…

Any help would be appreciated to help me understand the machinery behind that behavior. Can’t say it’s a bug because I suppose it’s not intended to be used like that at first, but still, the interaction between the test and the `wire:model` is somewhat frustrating…

**Comment by dominiquevilain** [comment]
Ok, just fixed it I think… 
Setting the `wire:key` for every item did the trick. The `$qp` variable contains the query parameters.

```php
<select name="perPage"
              wire:model="perPage"
              class="form-control"
              id="perPage">{{$perPage}}
                    <option wire:key="10" @if($qp['perPage'] === 10) selected @endif>10</option>
                    <option wire:key="15" @if($qp['perPage'] === 15) selected @endif>15</option>
                    <option wire:key="25" @if($qp['perPage'] === 25) selected @endif>25</option>
</select>
```

**Comment by crivion** [comment]
Here's the solution in case anyone else is beating their head to the table:

Just don't refresh the select and no need to add "selected"

<div wire:ignore>
<select wire:model="mode-name-here">
<option>1</option>
<option>2</option>
<option>3</option>
</select>
</div>

**Comment by dhandarbeit-tk** [comment]
I suspect whats happening is that the browser selects the option on page load, but that never gets reported back to livewire.
Right now I am hotfixing that but just dispatching a "change" event on every select on page load..

**Comment by Sparkqy** [comment]
if anyone has the same problem, here is how I fixed it: 

1. I refused to use wire:ignore because I couldn't access the properties from the component, so the condition (for selecting default selected element(s)) didn't work
2. Instead I used wire:model to get default selected elements working
3. In javascript file I'm calling select2 initialization every time Livewire fire message.processed event

Now I'm able to see default selected options and select2 is properly initialized.

**Comment by sergiogordondolimpio** [comment]
Hello, 
In the case of ChrisJohnson-83, in this blade:

`<select id="role_id" wire:model="role_id">
    <option value="1" {{ $role_id == 1 ? 'selected="selected"' : '' }}>Owner</option>
    <option value="2" {{ $role_id == 2 ? 'selected="selected"' : '' }}>Collaborator</option>
</select>`

You only must to take off the "" in value of option, so this value now is an integer like role_id but not an string, and without the conditional:

`<select id="role_id" wire:model="role_id">
    <option value=1>Owner</option>
    <option value=2>Collaborator</option>
</select>`

That is the way I was be able to fix it.

**Comment by Yinci** [comment]
Seeing as this thread comes from 2019, and Livewire has been updated 2 major versions, it's surprising to see something like this still be an issue. However, reading all these comments, and testing some things, I think it's clear that this will _never_ be fixed, as this is against how Livewire is functioning. 

**Let me explain:** 
The Livewire component passes data to a view, and renders it using this data. Because of this, values get manipulated after the HTML is prepared. A simple test can be done with an `input`. When you give this `input` a value, and a `wire:model` linked to a variable with no value, the input is empty. This ties in to what @calebporzio has said about the select: 

> Also, Livewire intelligently sets selected states, so you can get rid of the manually echoing out `selected="selected"`

When the linked variable has a value that is in the select, it will automatically be selected on the first render. But, a lot of people forget this, as it doesn't feel natural. I hit this wall as well. Because HTML automatically sets the first option to render as selected, it _feels_ like it should be selected. However, Livewire has not gotten a value for this select yet. Therefore, on instant submit, it is still empty. 

The solution is however relatively simple, and all one has to do is set the value in the component, either the variable itself, or in the `mount` function, what @jiteshdhamaniya already mentioned: 

> That's all you have to do. But initially it won't be having any value, so you have to set value in mount method like this
> 
> ```
> public function mount(){
>    $this->status = 1;
> }
> ```
> 
> and then It will be automatically selected. You can do this in render method too incase you want to set every time component refreshes.

I feel like this issue could simply be closed by giving a hint to this behaviour on [the docs](https://laravel-livewire.com/docs/2.x/rendering-components#parameters).

**Comment by kunalm7865** [comment]
>  $this->status = 1;

Thanks

**Comment by stuartcusackie** [comment]
Here's a weird example where setting the value in mount does not work:

```
public function mount()
    {
        // I want my selects to default to max and min values
        $works = Work::all();
        $this->minYearFrom = $works->min("year");   // returns string: 2000
        $this->maxYearFrom = $works->max("year"); // returns string: 2020
        
        // This does not work
        $this->yearFrom = $this->minYearFrom;  
        $this->yearTo = $this->maxYearFrom;  

         // This does work. Why??
        $this->yearFrom = '2000';  
        $this->yearTo = '2020';
    }

```

**Comment by SushilMore1988** [comment]
> Seeing as this thread comes from 2019, and Livewire has been updated 2 major versions, it's surprising to see something like this still be an issue. However, reading all these comments, and testing some things, I think it's clear that this will _never_ be fixed, as this is against how Livewire is functioning.
> 
> **Let me explain:**
> The Livewire component passes data to a view, and renders it using this data. Because of this, values get manipulated after the HTML is prepared. A simple test can be done with an `input`. When you give this `input` a value, and a `wire:model` linked to a variable with no value, the input is empty. This ties in to what @calebporzio has said about the select:
> 
> > Also, Livewire intelligently sets selected states, so you can get rid of the manually echoing out `selected="selected"`
> 
> When the linked variable has a value that is in the select, it will automatically be selected on the first render. But, a lot of people forget this, as it doesn't feel natural. I hit this wall as well. Because HTML automatically sets the first option to render as selected, it _feels_ like it should be selected. However, Livewire has not gotten a value for this select yet. Therefore, on instant submit, it is still empty.
> 
> The solution is however relatively simple, and all one has to do is set the value in the component, either the variable itself, or in the `mount` function, what @jiteshdhamaniya already mentioned:
> 
> > That's all you have to do. But initially it won't be having any value, so you have to set value in mount method like this
> > ```
> > public function mount(){
> >    $this->status = 1;
> > }
> > ```
> > 
> > 
> > and then It will be automatically selected. You can do this in render method too incase you want to set every time component refreshes.
> 
> I feel like this issue could simply be closed by giving a hint to this behaviour on [the docs](https://laravel-livewire.com/docs/2.x/rendering-components#parameters).

Thanks this solves my problem too.

**Comment by iforaberepo** [comment]
I'm not sure why @SushilMore1988 thought the post from @Yinci was helpful. I would like to know exactly what in that post helped solve this problem and specifically how it was implemented. 

Adding a random `$this->status = 1` means absolutely nothing without context. Sticking that in my code did nothing, as expected. There needs to be a more clear and thorough explanation of how Livewire renders the select menu, including working code examples. 

I've also tried not setting the select attribute in the foreach and found that Livewire does not automatically set the select attribute on a select menu option. Again, nothing in my study of the docs and reading code samples has lead me to believe this actually would happen.

I've read all the previous comments and tried every code sample included and nothing solves this issue. Can someone post code samples of **actual working Livewire select menu** files so those still experiencing this problem can finally get a solution?

Thanks

**Comment by Yinci** [comment]
> Adding a random `$this->status = 1` means absolutely nothing without context. Sticking that in my code did nothing, as expected. There needs to be a more clear and thorough explanation of how Livewire renders the select menu, including working code examples.

@iforaberepo I understand that it's still not quite clear. Livewire is, after all, quite a jump from your normal use case in Laravel. I'll give you some code samples:

1. Example in which the select is NOT set: 

**Livewire component:**
```php
<?php

namespace App\Http\Livewire\Users;

use Livewire\Component;

class UpdateProfile extends Component
{
    public $statuses = [
        0 => 'active',
        1 => 'pending',
        2 => 'inactive',
    ];

    public $status;
    
    public function render()
    {
        return view('livewire.users.update-profile');
    }

     public function submit()
    {
        dd($this->status);
    }
}
```

**View:**
```html
<div>
    <form class="space-y-8" wire:submit.prevent="submit">
        <select wire:model="status">
            @foreach($statuses as $index => $selectStatus)
                <option value="{{ $index }}">{{ $selectStatus }}</option>
            @endforeach
        </select>

        <button type="submit">
            Submit
        </button
    </form>
</div
```

**Explanation:**
When opening this view, and __immediately__ clicking the submit button, the output for this code block will be `null`. This is because in Livewire, the value currently set for `$status` is `null`. However, because HTML by default displays the first option in a select, it _looks_ like an item is selected. 

2. Making it set:

There are 2 suggested ways of ensuring the value of `$status`: 

- Option 1; **the mount function**: 
 
```php
public function mount(){
    $this->status = 1;
}
```

The mount function, as [described](https://laravel-livewire.com/docs/2.x/rendering-components#parameters) under the tag 'Receiving Parameters', is the `__construct` method for Livewire components. 

When adding this function (I usually place it right above the `render` function), you can do things to your own wishes before the component is first initialized. By setting `$status` in the mount function, it will contain a value, and so when then immediately pressing the submit button, the output will be `1`; In my most use cases, the `mount` function is great for pre-filling variables from a model. This can easily be done using `$this->fill($model->getAttributes());`.

- Option 2; **default value**:

Instead of using the `mount` function, you can also simply set a default value when setting the public parameter. 
`public $status = 1;` will also give the same result. 

When playing around with these values, you will see that the select will change value upon first render, even though you haven't touched it. The same goes for inputs, checkboxes, textareas and such. When the `wire:model` is linked, Livewire handles all the necessary steps to fill the fields with data.

I hope this clears things up a bit more!

P.S. When typehinting these attributes, an exception will be thrown if the value is not type hinted as `nullable` (e.g. `?string`) when trying to access it without value.

**Comment by SushilMore1988** [comment]
> I'm not sure why @SushilMore1988 thought the post from @Yinci was helpful. I would like to know exactly what in that post helped solve this problem and specifically how it was implemented.
> 
> Adding a random `$this->status = 1` means absolutely nothing without context. Sticking that in my code did nothing, as expected. There needs to be a more clear and thorough explanation of how Livewire renders the select menu, including working code examples.
> 
> I've also tried not setting the select attribute in the foreach and found that Livewire does not automatically set the select attribute on a select menu option. Again, nothing in my study of the docs and reading code samples has lead me to believe this actually would happen.
> 
> I've read all the previous comments and tried every code sample included and nothing solves this issue. Can someone post code samples of **actual working Livewire select menu** files so those still experiencing this problem can finally get a solution?
> 
> Thanks

Hello from where I understand you have to set every preselected value in mount so it renders in html correctly.
So in my case
<?php

namespace App\Http\Livewire\Users;

use Livewire\Component;

class UpdateProfile extends Component
{
    public $statuses = [
        0 => 'active',
        1 => 'pending',
        2 => 'inactive',
    ];

    public $status;
    
    public function mount()
    {
         $user = Auth::user();
         //Here I set the value of user status. 
         //You can check if it is set or not and set status value accordingly
         $this->status = $user->status;
    }
    public function render()
    {
        return view('livewire.users.update-profile');
    }

     public function submit()
    {
        dd($this->status);
    }
}

**Comment by iforaberepo** [comment]
Thanks for the responses. This code really helps.

**Comment by Yinci** [comment]
> @Yinci & @SushilMore1988 - Thanks for the responses. This code really helps. It's still very "magical black box" kind of behavior that makes me nervous. I will have to dig deeper into the source to see how/why this works.

There's certain things I don't like either, such as the magic `$refresh` function, which doesn't quite have lots of documentation on it. I'd rather trigger such functions "manually", so I understand the black box magic. It's just getting used to.

**Comment by talhacan** [comment]
still isn't fixed

this is not working
```PHP
public function mount(){
    $this->status = 1;
}
```



this is not a solition because we need **wire:model**
> Unfortunately that didn't work. If I remove the `wire:model="role_id"` from the select element then the correct value is displayed but then obviously it doesn't work anymore in terms of saving changes via livewire.


this is working but not effective
# @davidpiesse 

> @LewisLarsen I use that without issue
> `<option value="">Select a category</option>` (make sure to remove the selected) and set your wire:model item to '' in your component and have it validate to an integer if you want to force a choice
> 
> alternatively you can set the default value to -1
> `<option value="-1">Select a category</option>`
> 
> validate you item to 'required|numeric|min:1'
> or 'digits_between:1,x' for example if you have X elements and each element is increasing in value. go with the first one :)

**Comment by rello86** [comment]
@LewisLarsen your solution doesn't work.
Anyone come up with a working solution?
thanks

**Comment by hosamalzagh** [comment]
not work for me

**Comment by piersgill312** [comment]
> Ok I figured this.
> to anybody who is still looking.
> 
> ```
> <select wire:model="status">
>                         <option value="1">  Approved </option>
>                         <option value="2">  Un-Approved </option>
> </select>
> ```
> 
> That's all you have to do. But initially it won't be having any value, so you have to set value in mount method like this
> 
> ```
> public function mount(){
>    $this->status = 1;
> }
> ```
> 
> and then It will be automatically selected. You can do this in render method too incase you want to set every time component refreshes.

This fixed it for me.
However I also made sure **to not put the selected="selected" tag in manually** as livewire appears to handle this automatically.

**Comment by syedajmal1998** [comment]
to all who is Still facing this issue use `wire:change` instead of `wire:model` this fixed my problem

**Comment by Hugob79** [comment]
I found a very simple solution. Here's the example:

 <select wire:model="Your-WIRE-MODEL-NAME" class="form-control">
                        @if ($Your-WIRE-MODEL-NAME == 'usuario')
                        <option value='usuario'>Usuario</option>
                        <option value="admin">Administrador</option>
                    @else
                        <option value="admin">Administrador</option>
                        <option value="usuario">Usuario</option> 
                    @endif
                    </select>
Hope find it useful. 
Saludos!

**Comment by emanuelErazo1** [comment]
hello , i am solution check if var is null or empty so var is value = option first.

**Comment by fritzfr** [comment]
> to all who is Still facing this issue use `wire:change` instead of `wire:model` this fixed my problem
> 
> ```
>             <select id="categoryID" wire:change="categoryID">
>                 <option @empty($data) selected="selected" @endempty>---------------</option>
>                 @foreach ($categoryModel->where("is_deleted",false) as $category)
>                 <option @isset($data) {{ $data->category_id == $category->id ? "selected":"" }}@endisset
>                     value="{{ $category->id }}">{{ $category->name }} </option>
>                 @endforeach
>             </select>
> ```

This is the only solution that seems to work for me. This is still broken.

**Comment by jamesautodude** [comment]
I'm having a weird issue inside of foreach situations. When I click edit on any item the first time, the dropdown selects the database value. But then when I click any others (and even the same one again), the value isn't prepopulated anymore.

I have the property resetting, I also have it setting correctly. The value echos out just fine too. It just doesn't automatically select the dropdown anymore until I refresh the page. Really weird.
